class ClientPacketHeader
  @LOGIN_REQUEST = 0x00
  @REGISTER_REQUEST = 0x01
  @CHANGE_AVATAR_REQUEST = 0x02
  @CREATE_ROOM_REQUEST = 0x03
  @CHANGE_TABLE_SETTING_REQUEST = 0x04
  @READY_UP_REQUEST = 0x05
  @SCORE_BOARD_REQUEST = 0x06
  @LEAVE_ROOM_REQUEST = 0x07
  @MOVE_TILE_REQUEST = 0x08
  @CLAIM_TILE_FROM_DISCARDS = 0x09
  @CLAIM_TILE_FROM_STACK = 0x0A
  @BROADCAST_MESSAGE_REQUEST = 0x0B
  @DISCARD_TILE_REQUEST = 0x0C
  @JOIN_ROOM_REQUEST = 0x0D
  @END_TURN_REQUEST = 0x0E